package views.frames;

import java.awt.Toolkit;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTabbedPane;
import views.tabs.FactoryTabs;

/**
 *
 * @author skuarch
 */
public class Shaper extends javax.swing.JFrame {

    /**
     * Creates new form Shaper
     */
    public Shaper() {
        initComponents();
        setLocationRelativeTo(getRootPane());
        setIconImage(Toolkit.getDefaultToolkit().getImage(Shaper.class.getResource("/views/images/sam_icon.png")));
        setTitle("Shaper");
    }

    public JComboBox getjComboBoxCollectors() {
        return jComboBoxCollectors;
    }

    public JLabel getjLabelMessage() {
        return jLabelMessage;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JMenu getjMenuFile() {
        return jMenuFile;
    }

    public JMenuItem getjMenuItemFilters() {
        return jMenuItemFilters;
    }

    public JMenuItem getjMenuItemManageChains() {
        return jMenuItemManageChains;
    }

    public JMenuItem getjMenuItemManagePipes() {
        return jMenuItemManagePipes;
    }

    public JMenuItem getjMenuItemMonitoringBandwidth() {
        return jMenuItemMonitoringBandwidth;
    }

    public JMenuItem getjMenuItemMonitoringChains() {
        return jMenuItemMonitoringChains;
    }

    public JMenuItem getjMenuItemMonitoringPipes() {
        return jMenuItemMonitoringPipes;
    }

    public JMenuItem getjMenuItemRulesLoad() {
        return jMenuItemRulesLoad;
    }

    public JMenuItem getjMenuItemRulesLoadDebug() {
        return jMenuItemRulesLoadDebug;
    }

    public JMenuItem getjMenuItemRulesOverview() {
        return jMenuItemRulesOverview;
    }

    public JMenuItem getjMenuItemRulesShow() {
        return jMenuItemRulesShow;
    }

    public JMenuItem getjMenuItemRulesUnload() {
        return jMenuItemRulesUnload;
    }

    public JMenuItem getjMenuItemSettingsOptions() {
        return jMenuItemSettingsOptions;
    }

    public JMenuItem getjMenuItemSettingsPorts() {
        return jMenuItemSettingsPorts;
    }

    public JMenuItem getjMenuItemSettingsProtocols() {
        return jMenuItemSettingsProtocols;
    }

    public JMenuItem getjMenuItemSettingsServiceLevel() {
        return jMenuItemSettingsServiceLevel;
    }

    public JMenuItem getjMenuItemSettingsTargets() {
        return jMenuItemSettingsTargets;
    }

    public JMenuItem getjMenuItemStartCollector() {
        return jMenuItemStartCollector;
    }

    public JMenuItem getjMenuItemStopCollector() {
        return jMenuItemStopCollector;
    }

    public JMenu getjMenuManage() {
        return jMenuManage;
    }

    public JMenu getjMenuMonitoring() {
        return jMenuMonitoring;
    }

    public JMenu getjMenuRulesRules() {
        return jMenuRulesRules;
    }

    public JMenu getjMenuSettings() {
        return jMenuSettings;
    }

    public JMenu getjMenuTools() {
        return jMenuTools;
    }

    public JTabbedPane getjTabbedPane() {
        return jTabbedPane;
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new FactoryTabs();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCollectors = new javax.swing.JComboBox();
        jLabelMessage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemClose = new javax.swing.JMenuItem();
        jMenuManage = new javax.swing.JMenu();
        jMenuItemManageChains = new javax.swing.JMenuItem();
        jMenuItemManagePipes = new javax.swing.JMenuItem();
        jMenuItemFilters = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItemSettingsTargets = new javax.swing.JMenuItem();
        jMenuItemSettingsPorts = new javax.swing.JMenuItem();
        jMenuItemSettingsProtocols = new javax.swing.JMenuItem();
        jMenuItemSettingsServiceLevel = new javax.swing.JMenuItem();
        jMenuItemSettingsOptions = new javax.swing.JMenuItem();
        jMenuRulesRules = new javax.swing.JMenu();
        jMenuItemRulesShow = new javax.swing.JMenuItem();
        jMenuItemRulesLoad = new javax.swing.JMenuItem();
        jMenuItemRulesLoadDebug = new javax.swing.JMenuItem();
        jMenuItemRulesUnload = new javax.swing.JMenuItem();
        jMenuItemRulesOverview = new javax.swing.JMenuItem();
        jMenuMonitoring = new javax.swing.JMenu();
        jMenuItemMonitoringChains = new javax.swing.JMenuItem();
        jMenuItemMonitoringPipes = new javax.swing.JMenuItem();
        jMenuItemMonitoringBandwidth = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMenuItemStopCollector = new javax.swing.JMenuItem();
        jMenuItemStartCollector = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Please select a shaper");

        jComboBoxCollectors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "please select a collector" }));

        jMenuFile.setText("File");

        jMenuItemClose.setText("close");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemClose);

        jMenuBar1.add(jMenuFile);

        jMenuManage.setText("Manage");
        jMenuManage.setEnabled(false);

        jMenuItemManageChains.setText("chains");
        jMenuManage.add(jMenuItemManageChains);

        jMenuItemManagePipes.setText("pipes");
        jMenuManage.add(jMenuItemManagePipes);

        jMenuItemFilters.setText("filters");
        jMenuManage.add(jMenuItemFilters);

        jMenuBar1.add(jMenuManage);

        jMenuSettings.setText("Settings");
        jMenuSettings.setEnabled(false);

        jMenuItemSettingsTargets.setText("targets");
        jMenuSettings.add(jMenuItemSettingsTargets);

        jMenuItemSettingsPorts.setText("ports");
        jMenuSettings.add(jMenuItemSettingsPorts);

        jMenuItemSettingsProtocols.setText("protocols");
        jMenuSettings.add(jMenuItemSettingsProtocols);

        jMenuItemSettingsServiceLevel.setText("service level");
        jMenuSettings.add(jMenuItemSettingsServiceLevel);

        jMenuItemSettingsOptions.setText("options");
        jMenuSettings.add(jMenuItemSettingsOptions);

        jMenuBar1.add(jMenuSettings);

        jMenuRulesRules.setText("Rules");
        jMenuRulesRules.setEnabled(false);

        jMenuItemRulesShow.setText("show");
        jMenuRulesRules.add(jMenuItemRulesShow);

        jMenuItemRulesLoad.setText("load");
        jMenuRulesRules.add(jMenuItemRulesLoad);

        jMenuItemRulesLoadDebug.setText("load debug");
        jMenuRulesRules.add(jMenuItemRulesLoadDebug);

        jMenuItemRulesUnload.setText("unload");
        jMenuRulesRules.add(jMenuItemRulesUnload);

        jMenuItemRulesOverview.setText("overview");
        jMenuRulesRules.add(jMenuItemRulesOverview);

        jMenuBar1.add(jMenuRulesRules);

        jMenuMonitoring.setText("Monitoring");
        jMenuMonitoring.setEnabled(false);

        jMenuItemMonitoringChains.setText("chains");
        jMenuMonitoring.add(jMenuItemMonitoringChains);

        jMenuItemMonitoringPipes.setText("pipes");
        jMenuMonitoring.add(jMenuItemMonitoringPipes);

        jMenuItemMonitoringBandwidth.setText("bandwidth");
        jMenuMonitoring.add(jMenuItemMonitoringBandwidth);

        jMenuBar1.add(jMenuMonitoring);

        jMenuTools.setText("Tools");
        jMenuTools.setEnabled(false);

        jMenuItemStopCollector.setText("stop collector");
        jMenuTools.add(jMenuItemStopCollector);

        jMenuItemStartCollector.setText("start collector");
        jMenuTools.add(jMenuItemStartCollector);

        jMenuBar1.add(jMenuTools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxCollectors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCollectors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxCollectors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemFilters;
    private javax.swing.JMenuItem jMenuItemManageChains;
    private javax.swing.JMenuItem jMenuItemManagePipes;
    private javax.swing.JMenuItem jMenuItemMonitoringBandwidth;
    private javax.swing.JMenuItem jMenuItemMonitoringChains;
    private javax.swing.JMenuItem jMenuItemMonitoringPipes;
    private javax.swing.JMenuItem jMenuItemRulesLoad;
    private javax.swing.JMenuItem jMenuItemRulesLoadDebug;
    private javax.swing.JMenuItem jMenuItemRulesOverview;
    private javax.swing.JMenuItem jMenuItemRulesShow;
    private javax.swing.JMenuItem jMenuItemRulesUnload;
    private javax.swing.JMenuItem jMenuItemSettingsOptions;
    private javax.swing.JMenuItem jMenuItemSettingsPorts;
    private javax.swing.JMenuItem jMenuItemSettingsProtocols;
    private javax.swing.JMenuItem jMenuItemSettingsServiceLevel;
    private javax.swing.JMenuItem jMenuItemSettingsTargets;
    private javax.swing.JMenuItem jMenuItemStartCollector;
    private javax.swing.JMenuItem jMenuItemStopCollector;
    private javax.swing.JMenu jMenuManage;
    private javax.swing.JMenu jMenuMonitoring;
    private javax.swing.JMenu jMenuRulesRules;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
