package views.frames;

import java.awt.Toolkit;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import views.tabs.FactoryTabs;

/**
 *
 * @author skuarch
 */
public class Sniffer extends javax.swing.JFrame {

    //==========================================================================
    /**
     * Creates new form Sniffer
     */
    public Sniffer() {        
        initComponents();        
        setLocationRelativeTo(getRootPane());
        setIconImage(Toolkit.getDefaultToolkit().getImage(MainFrame.class.getResource("/views/images/sam_icon.png")));
    }

    public JTabbedPane getjTabbedPaneViews() {
        return jTabbedPaneViews;
    }    

    public JTabbedPane getjTabbedPaneCollectors() {
        return jTabbedPaneCollectors;
    }

    public JSplitPane getjSplitPaneMain() {
        return jSplitPaneMain;
    }

    public JSplitPane getjSplitPaneTrees() {
        return jSplitPaneTrees;
    }

    public JMenuItem getjMenuItemSearchIPAddress() {
        return jMenuItemSearchIPAddress;
    }

    public JMenuItem getjMenuItemSearchPort() {
        return jMenuItemSearchPort;
    }

    public JMenu getjMenuTools() {
        return jMenuTools;
    }   

    public JMenuItem getjMenuItemSearchSubnet() {
        return jMenuItemSearchSubnet;
    }    

    public JMenuItem getjMenuItemCreateReport() {
        return jMenuItemCreateReport;
    }

    //==========================================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneMain = new javax.swing.JSplitPane();
        jSplitPaneTrees = new javax.swing.JSplitPane();
        jTabbedPaneViews = new FactoryTabs();
        jTabbedPaneCollectors = new FactoryTabs();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTools = new javax.swing.JMenu();
        jMenuItemSearchIPAddress = new javax.swing.JMenuItem();
        jMenuItemSearchPort = new javax.swing.JMenuItem();
        jMenuItemSearchSubnet = new javax.swing.JMenuItem();
        jMenuItemCreateReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPaneMain.setDividerLocation(250);

        jSplitPaneTrees.setDividerLocation(250);
        jSplitPaneTrees.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPaneTrees.setTopComponent(jTabbedPaneViews);
        jSplitPaneTrees.setRightComponent(jTabbedPaneCollectors);

        jSplitPaneMain.setLeftComponent(jSplitPaneTrees);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/sniffer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jSplitPaneMain.setRightComponent(jPanel1);

        jMenuTools.setText("Tools");

        jMenuItemSearchIPAddress.setText("search ip address");
        jMenuTools.add(jMenuItemSearchIPAddress);

        jMenuItemSearchPort.setText("search port");
        jMenuTools.add(jMenuItemSearchPort);

        jMenuItemSearchSubnet.setText("search subnet");
        jMenuTools.add(jMenuItemSearchSubnet);

        jMenuItemCreateReport.setText("create report");
        jMenuTools.add(jMenuItemCreateReport);

        jMenuBar1.add(jMenuTools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCreateReport;
    private javax.swing.JMenuItem jMenuItemSearchIPAddress;
    private javax.swing.JMenuItem jMenuItemSearchPort;
    private javax.swing.JMenuItem jMenuItemSearchSubnet;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPaneMain;
    private javax.swing.JSplitPane jSplitPaneTrees;
    private javax.swing.JTabbedPane jTabbedPaneCollectors;
    private javax.swing.JTabbedPane jTabbedPaneViews;
    // End of variables declaration//GEN-END:variables
}
