package views.dialogs;

import controllers.global.ControllerNotifications;
import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import model.util.HashMapUtilities;

/**
 *
 * @author skuarch
 */
public class Detail extends javax.swing.JDialog {

    private HashMap hashMap = null;
    private static final ControllerNotifications NOTIFICATIONS = new ControllerNotifications();

    /**
     * Creates new form Detail
     */
    public Detail(java.awt.Frame parent, boolean modal, HashMap hashmap) {
        super(parent, modal);
        this.hashMap = hashmap;
        initComponents();
        onLoad();
    }

    //==========================================================================
    private void onLoad() {

        try {

            setLocationRelativeTo(getRootPane());
            setIconImage(Toolkit.getDefaultToolkit().getImage(Detail.class.getResource("/views/images/sam_icon.png")));

            setTitle("Details");
            String[] columNames = {"Properties", "Values"};
            jTable1.setModel(new DefaultTableModel(HashMapUtilities.hashMapsToArray(hashMap), columNames));

        } catch (Exception e) {
            NOTIFICATIONS.error("error creating dialog", e);
        }

    } // end onLoad

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}