package views.dialogs;

import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JProgressBar;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;

/**
 *
 * @author skuarch
 */
public class LiveChartPipes extends javax.swing.JDialog {

    //==========================================================================
    /**
     * Creates new form LiveChartChains
     */
    public LiveChartPipes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(getRootPane());
        setIconImage(Toolkit.getDefaultToolkit().getImage(LiveChartPipes.class.getResource("/views/images/sam_icon.png")));
        setTitle("Traffic Monitoring Pipes");
        buttonGroup.add(jRadioButtonIncoming);
        buttonGroup.add(jRadioButtonOutComing);
    }

    public ButtonGroup getButtonGroup() {
        return buttonGroup;
    }

    public JButton getjButtonClose() {
        return jButtonClose;
    }

    public JButton getjButtonReload() {
        return jButtonReload;
    }

    public JComboBox getjComboBoxScale() {
        return jComboBoxScale;
    }

    public JProgressBar getjProgressBar() {
        return jProgressBar;
    }

    public JRadioButton getjRadioButtonIncoming() {
        return jRadioButtonIncoming;
    }

    public JRadioButton getjRadioButtonOutComing() {
        return jRadioButtonOutComing;
    }

    public JTabbedPane getjTabbedPane() {
        return jTabbedPane;
    }

    public JComboBox getjComboBoxSeconds() {
        return jComboBoxSeconds;
    }

    public JComboBox getjComboBoxPipes() {
        return jComboBoxPipes;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonIncoming = new javax.swing.JRadioButton();
        jRadioButtonOutComing = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxScale = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPipes = new javax.swing.JComboBox();
        jButtonReload = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jButtonClose = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSeconds = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Traffic direction:");

        jRadioButtonIncoming.setSelected(true);
        jRadioButtonIncoming.setText("incoming");

        jRadioButtonOutComing.setText("outcoming");

        jLabel2.setText("Scale:");

        jComboBoxScale.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bit/s", "byte/s", "kbit/s", "kbyte/s", "mbit/s", "mbyte/s" }));

        jLabel3.setText("Chain");

        jComboBoxPipes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "please select a pipe" }));

        jButtonReload.setText("create graph");

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/shutdown-mini.png"))); // NOI18N
        jButtonClose.setText("close");

        jTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel4.setText("Seconds");

        jComboBoxSeconds.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "60", "120" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonOutComing)
                            .addComponent(jRadioButtonIncoming)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxScale, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxPipes, 0, 140, Short.MAX_VALUE)
                            .addComponent(jButtonReload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxSeconds, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonClose))
                    .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonIncoming)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonOutComing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPipes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(jButtonReload))
                    .addComponent(jTabbedPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonReload;
    private javax.swing.JComboBox jComboBoxPipes;
    private javax.swing.JComboBox jComboBoxScale;
    private javax.swing.JComboBox jComboBoxSeconds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButtonIncoming;
    private javax.swing.JRadioButton jRadioButtonOutComing;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
